name: hiltonSample
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

module:
  androidX: true


dependency_overrides:
  intl: any

dependencies:
  font_awesome_flutter: ^8.10.0
  google_fonts: ^1.1.1
  package_info: ^0.4.3+2
  shimmer: ^1.1.2
  flutter_staggered_animations: ^0.1.3
  progress_dialog: ^1.2.1
  json_annotation: ^2.0.0
  url_launcher: ^5.0.3
  xml: ^4.5.1
  country_code_picker: 1.2.4
  flutter_rating_bar: 3.0.1+1
  pin_view: 1.0.1
  toast: 0.1.5
  shared_preferences: 0.5.6+3
  built_value: ^6.7.1
  rxdart: ^0.23.1
  image_picker: ^0.6.7+11
  dotted_border: ^1.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"
  flutter_automation: ^1.3.3
  cached_network_image: ^2.3.2+1
  cupertino_icons: ^0.1.2
  geocoder: ^0.2.1
  flutter_native_splash: ^0.1.9
  geolocator: ^5.1.4+2
  location: ^2.5.0
  location_permissions: ^2.0.5
  google_maps_flutter: 0.5.21+12
  flutter_plugin_android_lifecycle: ^1.0.11
  search_map_place: 0.3.0
  http: 0.12.1
  intl: 0.16.1
  firebase_auth: 0.16.0
  firebase_database: 3.1.5
  firebase_storage: 3.1.5
  firebase_core: 0.4.5


dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  built_value_generator: ^6.7.1
  flutter_test:
    sdk: flutter
  # Your other dev_dependencies here

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - i18n/en.json
    - i18n/cars.json
    - asset/images/
    - asset/images/f_logo.jpg
    - asset/images/car.jpg
    - asset/images/ci.jpg
    - asset/images/cm.jpg
    - asset/images/cp.jpg
    - asset/images/cw.jpg
    - asset/images/login_bg.png
    - asset/images/gps.png
    - asset/images/register_bg.png
    - asset/images/splash.gif

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Black.ttf
          weight: 900
    - family: RobotoCondensed
      fonts:
        - asset: fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: fonts/RobotoCondensed-Regular.ttf
          weight: 400
        - asset: fonts/RobotoCondensed-Bold.ttf
          weight: 500



